<div id="community-vibe">
    <h2 class="sect-title">Community Vibe in Parkdale</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">The Parkdale Community Association operates a community hall, with wheelchair access, a commercial kitchen, sound system and outdoor bbq; they also run sports and youth justice programs. </p>
            <p class="par-lg">The City of Calgary maintains an outdoor skating rink and tennis courts. </p>
            <p class="par-lg">Parkdale is a short distance from Kensington Business Revitalization Zone, one of Calgary’s most popular destinations for shopping and dining. </p>
            <p class="par-lg">Apart from the assortment of owner-run shops and famous restaurants, people will find themselves drawn to the area’s friendly nature and artistic atmosphere, the area being overlooked by the Alberta College of Art and Design (ACAD). </p>

        </div>
        <div>
            <div class="lightbox-gallery">
            <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/edworthy-park-bow-river-view-from-bridge.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/edworthy-park-bow-river-view-from-bridge.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/edworthy-park-bow-river-view-from-trail.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/edworthy-park-bow-river-view-from-trail.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/edworthy-park-jogging-trails.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/edworthy-park-jogging-trails.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/edworthy-park-sign.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/edworthy-park-sign.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/foothills-hospital-entrance.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/foothills-hospital-entrance.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/foothills-hospital-memorial-drive.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/foothills-hospital-memorial-drive.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/lift-chair-ski-shop-parkdale-strip-mall.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/lift-chair-ski-shop-parkdale-strip-mall.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/memorial-drive-and-kensington-drive-parkdale.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/memorial-drive-and-kensington-drive-parkdale.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/memorial-drive-east-of-crowchild-downtown-view.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/memorial-drive-east-of-crowchild-downtown-view.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/memorial-drive-shaganappi-exit.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/memorial-drive-shaganappi-exit.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/modern-home-parkdale.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/modern-home-parkdale.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-baseball-diamond.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-baseball-diamond.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-centre-beach-volleyball-courts.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-centre-beach-volleyball-courts.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-centre-sign.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-centre-sign.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-centre-skating-rink-beach-volleyball-courts.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-centre-skating-rink-beach-volleyball-courts.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-centre.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-centre.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-park.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-park.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-playground.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-community-playground.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-detached-homes.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-detached-homes.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-elementary-school-entrance.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-elementary-school-entrance.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-elementary-school.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-elementary-school.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-garden.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-garden.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-grace-fellowship.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-grace-fellowship.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-park-and-ball-diamond.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-park-and-ball-diamond.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-park-overlooking-foothills-hospital.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-park-overlooking-foothills-hospital.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-playground.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-playground.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-school-crossing-sign.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-school-crossing-sign.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-street-view-from-foothills-hospital.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-street-view-from-foothills-hospital.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-strip-mall-dentist.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-strip-mall-dentist.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-view-from-foothills.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/parkdale-view-from-foothills.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/residence-university-of-calgary.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/residence-university-of-calgary.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/row-of-homes-parkdale.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/row-of-homes-parkdale.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/strip-mall-parkdale-memorial-drive.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/strip-mall-parkdale-memorial-drive.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/strip-mall-parkdale.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/strip-mall-parkdale.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/traditional-home-parkdale.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/traditional-home-parkdale.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/tree-lined-apartment-building-parkdale.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/tree-lined-apartment-building-parkdale.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/tree-lined-parkdale.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/tree-lined-parkdale.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/tree-lined-street-parkdale.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/tree-lined-street-parkdale.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/tudor-home-parkdale.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/tudor-home-parkdale.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-buliding.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-buliding.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-entrance.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-entrance.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-pathway.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-pathway.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-sign.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-sign.webp" alt=""> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-students-walking-pathway.webp" data-gallery="gallery1" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/university-of-calgary-students-walking-pathway.webp" alt=""> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/community/central-calgary/parkdale/westmount-charter-school-parkdale.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>

        </div>

    </div>
</div>