<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Bayside</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">Many of the listed properties in the neighborhood of Bayside are located on the beautiful Pier 11. </p>
            <p class="par-lg">The real estate in Bayside also includes apartment complexes, water-facing condos and multi-story bungalows all of which are connected to Pier 11 via tree-lined pathways. </p>
            <p class="par-lg">Some of the properties on sale are fully furnished while others are semi-furnished. </p>
            <p class="par-lg">Many of the houses also have large gardens, garden sheds, front and back yards and parking spaces.</p>
        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-1.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-1.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-10.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-10.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-11.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-11.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-12.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-13.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-14.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-15.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-16.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-17.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-17.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-18.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-18.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-19.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-19.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-2.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-2.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-20.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-20.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-21.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-21.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-22.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-22.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-23.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-23.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-24.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-24.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-25.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-25.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-26.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-26.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-27.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-27.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-28.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-28.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-29.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-29.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-3.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-3.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-30.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-30.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-31.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-31.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-32.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-32.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-33.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-33.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-34.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-34.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-35.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-35.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-36.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-36.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-37.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-37.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-38.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-38.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-39.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-39.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-4.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-4.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-40.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-40.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-41.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-41.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-42.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-42.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-43.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-43.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-44.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-44.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-45.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-45.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-46.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-46.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-47.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-47.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-48.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-48.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-49.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-49.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-5.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-5.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-50.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-50.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-6.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-6.webp" alt="Community photo in Bayside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-7.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-7.webp" alt="Community photo in Bayside, Airdrie"> </a>

            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/bayside/bayside-8.webp" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>