<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Reunion</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">Reunion also has multiple enclave lots where home buyers can have up-market homes constructed. </p>
            <p class="par-lg">Multiple planned communities are being developed here, with each community having world-class amenities such as shopping malls, restaurants, movie theaters, jogging tracks, biking zones and more. </p>
            <p class="par-xl">There are lots of green spaces, pathways, and ponds around Reunion. </p>
            <p class="par-xl">This is the ideal place to start and raise a family.</p>
        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-11.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-11.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-12.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-13.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-14.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-15.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-16.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-18.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-18.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-19.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-19.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-2.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-2.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-20.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-20.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-21.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-21.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-22.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-22.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-23.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-23.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-24.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-24.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-25.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-25.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-26.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-26.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-27.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-27.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-28.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-28.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-29.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-29.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-3.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-3.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-30.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-30.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-31.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-31.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-32.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-32.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-33.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-33.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-34.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-34.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-35.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-35.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-36.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-36.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-37.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-37.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-38.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-38.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-39.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-39.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-4.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-4.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-40.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-40.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-41.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-41.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-5.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-5.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-6.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-6.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-7.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-7.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-8.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-8.webp" alt="Community photo in Reunion, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-9.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-9.webp" alt="Community photo in Reunion, Airdrie"> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/reunion/reunion-1.webp" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>