<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Ravenswood</h2>
    <div class="col-grid-2">
        <div>
        <p class="par-lg">Even if you are looking for massive estate homes in the community in Ravenswood, you don't really need to have a million dollar budget to acquire your dream property in this part of the town. </p>
        <p class="par-xl">Homes for sale in Ravenswood offer great access to modern amenities such as schools, malls, public transportation and so on. </p>
        <p class="par-lg">While a laned home can be yours for a starting price along the lines of 400s, you can purchase an estate home for as reasonable as mid 500s.</p>
        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-11.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-11.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-12.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-13.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-14.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-15.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-16.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-17.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-17.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-18.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-18.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-19.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-19.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-2.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-2.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-20.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-20.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-21.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-21.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-22.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-22.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-23.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-23.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-24.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-24.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-25.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-25.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-26.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-26.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-27.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-27.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-28.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-28.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-29.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-29.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-3.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-3.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-30.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-30.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-4.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-4.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-5.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-5.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-6.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-6.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-7.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-7.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-8.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-8.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-9.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-9.webp" alt="Community photo in Ravenswood, Airdrie"> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/ravenswood/ravenswood-10.webp" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>