<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Woodside</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">The real estate in Woodside includes large suburban houses. </p>
            <p class="par-lg">From single story homes to duplex houses, different types of buildings are available for sale. </p>
            <p class="par-lg">Garage-attached homes are also available. </p>
            <p class="par-xl">From simple apartments to fully furnished condos, real estate investors can find a wide range of buildings worthy of investment. </p>
            <p class="par-lg">The Woodside Golf Course is located here. </p>
            <p class="par-lg">This is one of the largest and most beautiful golf courses in Canada. </p>
            <p class="par-lg">Lush parks dot the neighborhood and there are designated areas for jogging and biking.</p>
        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-11.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-11.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-12.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-13.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-14.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-15.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-16.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-17.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-17.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-18.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-18.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-19.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-19.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-2.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-2.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-20.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-20.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-21.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-21.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-22.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-22.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-23.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-23.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-24.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-24.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-25.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-25.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-3.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-3.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-4.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-4.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-5.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-5.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-6.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-6.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-7.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-7.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-8.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-8.webp" alt="Community photo in Woodside, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-9.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-9.webp" alt="Community photo in Woodside, Airdrie"> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/woodside/woodside-10.webp" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>