<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Cooper's Crossing</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">Cooper's Crossing has a pristine location with plenty of green spaces and modern amenities, enough to lure relaxation-seeking urban dwellers. </p>
            <p class="par-lg">Cooper's Crossing Real Estate provides everything a family would need for a comfortable living. </p>
            <p class="par-lg">Starting from estate homes and single family units to luxurious villas, townhouses, and condos, Cooper's Crossing is an ideal destination for individual professionals and families. </p>
            <p class="par-lg">The average price of Cooper's Crossing Real Estate is $646,000. </p>
            <p class="par-lg">Shopping centers, schools, trails and parkland dotting the region make for the perfect lifestyle people wish to lead.</p>
        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-10.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-10.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-11.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-11.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-12.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-13.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-14.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-15.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-16.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-17.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-17.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-18.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-18.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-19.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-19.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-2.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-2.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-20.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-20.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-21.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-21.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-22.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-22.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-23.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-23.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-24.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-24.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-25.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-25.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-26.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-26.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-27.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-27.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-28.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-28.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-29.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-29.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-3.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-3.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-30.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-30.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-31.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-31.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-32.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-32.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-33.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-33.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-34.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-34.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-35.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-35.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-36.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-36.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-37.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-37.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-38.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-38.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-39.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-39.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-4.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-4.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-40.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-40.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-41.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-41.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-42.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-42.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-43.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-43.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-5.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-5.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-6.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-6.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-7.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-7.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-8.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-8.webp" alt="Community photo in Cooper's Crossing, Airdrie"> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/coppers-crossing/coppers-crossing-9.webp" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>