<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Jensen</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">The real estate in Jensen includes single story condos and semi-detached bungalows, among others. </p>
            <p class="par-lg">Large front yards and expansive backyards are the unique features of the houses in this neighborhood. </p>
            <p class="par-lg">There are multiple parks and playgrounds where children can play and parents can unwind. </p>
            <p class="par-lg">The houses here are constructed in traditional architectural designs with large patios and tiled roofs. </p>
            <p class="par-lg">Being a pet-loving neighborhood, there are multiple pet food stores in and around the area.</p>
        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-11.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-11.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-12.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-13.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-14.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-15.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-16.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-17.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-17.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-18.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-18.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-19.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-19.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-2.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-2.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-20.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-20.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-21.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-21.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-22.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-22.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-23.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-23.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-24.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-24.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-25.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-25.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-26.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-26.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-27.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-27.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-28.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-28.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-29.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-29.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-3.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-3.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-30.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-30.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-31.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-31.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-32.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-32.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-33.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-33.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-34.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-34.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-35.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-35.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-4.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-4.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-5.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-5.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-6.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-6.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-7.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-7.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-8.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-8.webp" alt="Community photo in Jensen, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-9.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-9.webp" alt="Community photo in Jensen, Airdrie"> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/jensen/jensen-10.webp" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>