<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Maple Way Meadowbrook</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">A quiet and affordable neighborhood, the community in Maple Way Meadowbrook promises a great quality of living on the lap of Mother Nature. </p>
            <p class="par-xl">With prices starting at around the mid 300s, the homes for sale in Maple Way Meadowbrook offer the residents a variety of options to choose from. </p>
            <p class="par-lg">The maple Way Meadowbrook Real Estate offers a plethora of recreational pursuits for the residents to revel in.</p>
        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-11.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-11.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-12.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-13.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-14.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-15.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-16.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-17.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-17.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-18.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-18.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-19.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-19.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-2.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-2.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-20.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-20.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-21.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-21.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-22.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-22.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-23.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-23.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-24.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-24.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-25.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-25.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-26.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-26.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-27.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-27.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-28.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-28.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-29.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-29.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-3.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-3.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-30.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-30.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-31.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-31.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-32.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-32.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-33.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-33.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-4.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-4.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-5.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-5.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-6.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-6.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-7.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-7.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-8.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-8.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-9.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-9.webp" alt="Community photo in Meadowbrook, Airdrie"> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/meadowbrook/meadowbrook-10.webp" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>