<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Prairie Springs</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">In the recent times, Airdrie has become a bedroom community owing to the fact that it is only six kilometers from the city of Calgary and a mere twenty minutes' drive from Calgary International Airport. </p>
            <p class="par-xl">The recreational activities, commercial centers, and the aesthetic landscape have brought a number of residents to the community. </p>
            <p class="par-lg">Prairie Springs real estate listings have an average price of $365,000 ($263 per square foot), with an influx of luxurious condominiums.</p>


        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-11.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-11.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-12.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-13.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-14.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-15.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-16.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-18.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-18.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-19.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-19.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-2.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-2.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-20.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-20.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-21.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-21.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-22.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-22.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-23.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-23.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-24.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-24.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-25.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-25.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-26.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-26.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-27.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-27.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-28.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-28.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-29.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-29.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-3.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-3.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-30.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-30.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-31.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-31.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-32.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-32.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-33.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-33.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-34.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-34.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-35.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-35.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-36.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-36.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-37.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-37.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-38.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-38.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-39.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-39.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-4.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-4.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-40.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-40.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-41.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-41.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-42.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-42.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-43.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-43.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-44.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-44.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-45.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-45.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-46.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-46.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-47.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-47.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-48.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-48.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-49.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-49.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-5.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-5.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-50.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-50.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-51.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-51.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-52.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-52.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-53.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-53.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-6.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-6.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-7.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-7.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-8.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-8.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-9.webp" class="glightbox hidden" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-9.webp" alt="Community photo in Prairie Springs, Airdrie"> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/prairie-springs/prairie-springs-10.webp" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>