<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Hillcrest</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">Hillcrest community in Airdrie combines convenience and luxury to create one of the best residential neighborhoods in the region. </p>
            <p class="par-lg">The average asking price of Hillcrest real estate is in the range of $450,000 and $500,000. </p>
            <p class="par-lg">When the size of the properties is considered, it is often seen that they have fewer bedrooms than most of the houses available in the country. </p>
            <p class="par-lg">Homes for sale in Hillcrest include all types- from single homes with front garage to townhouses and condos that a family would need to live comfortably.</p>
        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-11.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-11.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-12.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-13.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-14.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-15.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-16.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-17.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-17.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-18.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-18.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-19.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-19.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-2.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-2.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-20.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-20.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-21.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-21.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-22.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-22.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-23.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-23.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-24.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-24.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-25.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-25.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-26.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-26.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-27.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-27.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-28.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-28.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-29.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-29.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-3.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-3.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-30.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-30.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-31.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-31.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-32.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-32.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-33.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-33.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-34.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-34.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-35.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-35.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-4.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-4.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-5.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-5.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-6.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-6.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-7.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-7.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-8.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-8.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-9.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-9.webp" alt="Community photo in Hillcrest, Airdrie"> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/hillcrest/hillcrest-10.webp" data-gallery="gallery1" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>