<div id="about-the-community" class="section-spacer">
    <h2 class="sect-title">About Luxstone</h2>
    <div class="col-grid-2">
        <div>
            <p class="par-lg">The real estate in Luxstone comprises of fully developed bungalows, upgraded condos, apartment complexes and single and multi-story buildings. </p>
            <p class="par-lg">Many of the listed properties in the Luxstone neighborhood have attached garages and parking spaces. </p>
            <p class="par-lg">They also have expansive front yards, back yards and gardens, all of which are ideal for summertime barbeque parties. </p>
            <p class="par-lg">There are many lush green parks and playgrounds dotting the neighborhood. </p>
            <p class="par-lg">You will also find restaurants, cafes and bakeries here.</p>
        </div>
        <div>
            <div class="lightbox-gallery">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-11.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-11.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-12.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-12.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-13.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-13.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-14.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-14.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-15.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-15.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-16.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-16.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-17.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-17.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-18.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-18.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-19.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-19.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-2.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-2.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-20.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-20.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-21.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-21.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-22.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-22.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-23.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-23.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-24.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-24.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-25.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-25.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-26.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-26.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-27.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-27.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-28.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-28.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-29.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-29.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-3.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-3.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-30.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-30.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-31.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-31.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-32.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-32.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-33.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-33.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-4.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-4.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-5.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-5.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-6.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-6.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-7.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-7.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-8.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-8.webp" alt="Community photo in Luxstone, Airdrie"> </a>
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-9.webp" class="glightbox" rel="noindex nofollow"> <img class="lazyload hidden" data-src="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-9.webp" alt="Community photo in Luxstone, Airdrie"> </a>
            </div>
            <div style="text-align: center; padding: 2rem 0; color: #b11107; font-weight: 600;">
                <a href="https://www.calgary-real-estate.com/uploads/agent-1/airdrie/luxstone/luxstone-10.webp" class="glightbox" rel="noindex nofollow">View Image Gallery</a>
            </div>
        </div>
    </div>
</div>